reviewers:
  # The default lead reviewers.
  # Reviews may only be requested from collaborators.
  # TODO (Sakhno V): Add lead reviewers usernames.
  defaults:
    - lead_reviewer_1
    - lead_reviewer_2
